name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.9
  - snakemake=8.11.3
  - python-dotenv=1.0.1
  - requests=2.31.0
  - scikit-learn=1.4.2
  - rouge=1.0.1
  - matplotlib=3.8.4
  - pandas=2.2.2
  - markdownify=0.11.6
  - bs4=4.12.3
  - langchain=0.1.20
  - graphviz=9.0.0
  - ragas=0.1.7
  - pip=24.0
  - pip:
    - deepeval=0.21.42
